FROM ubuntu:bionic
MAINTAINER Frank Liu <bounce@frankliu.io>
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -qy \
    texlive-full \
    python-pygments gnuplot \
    make git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /source
VOLUME ["/source"]
